# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83ba53780fdbef5c70ef6dccc10b5ccd46cd3843ab3d99cb3775bb2ede34324d778f568d3f65e666583076e6089d7da5a204ab56f482596b08ce2db3582e52d9

test:
  secret_key_base: c7a1892d1f3b9cbdbccdf2471e55a74110c79512546508cfa96b7ef2ffd539e43bae00cd1b9e91309f4d5db66a4c9787ea75ca67db560fd2e0bf35c1cfeb57e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
